package config

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
)

const DefaultPath = "/etc/marzwatch/config.json"

type Config struct {
	Role            string `json:"role"`
	Name            string `json:"name"`
	Listen          string `json:"listen,omitempty"`
	PublicIP        string `json:"public_ip,omitempty"`
	Timezone        string `json:"timezone,omitempty"`
	TelegramToken   string `json:"telegram_token,omitempty"`
	AdminChatID     int64  `json:"admin_chat_id,omitempty"`
	JoinToken       string `json:"join_token,omitempty"`
	CentralURL      string `json:"central_url,omitempty"`
	CertFingerprint string `json:"cert_fingerprint,omitempty"`
}

func Load(path string) (Config, error) {
	if path == "" {
		path = DefaultPath
	}
	b, err := os.ReadFile(path)
	if err != nil {
		return Config{}, err
	}
	var c Config
	if err := json.Unmarshal(b, &c); err != nil {
		return Config{}, err
	}
	if c.Role != "central" && c.Role != "agent" {
		return Config{}, errors.New("invalid role")
	}
	return c, nil
}

func Save(path string, c Config) error {
	if path == "" {
		path = DefaultPath
	}
	if err := os.MkdirAll(filepath.Dir(path), 0750); err != nil {
		return err
	}
	b, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, b, 0640); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func RandomToken(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

// ParseJoinKey keeps support for the original MW1 token format.
// Existing deployed agents do not need this function after registration,
// but keeping it avoids breaking older tooling/tests.
func ParseJoinKey(k string) (token, fingerprint string, err error) {
	parts := strings.Split(strings.TrimSpace(k), ".")
	if len(parts) != 3 || parts[0] != "MW1" {
		return "", "", fmt.Errorf("invalid join key")
	}
	if len(parts[1]) < 32 || len(parts[2]) != 64 {
		return "", "", fmt.Errorf("invalid join key")
	}
	return parts[1], strings.ToLower(parts[2]), nil
}

// ParseNodeToken parses the self-contained MW2 token generated by Central.
// Format: MW2@CENTRAL_IP@JOIN_SECRET@TLS_SHA256_FINGERPRINT
// The agent therefore needs only a node name and this single token.
func ParseNodeToken(k string) (centralIP, token, fingerprint string, err error) {
	parts := strings.Split(strings.TrimSpace(k), "@")
	if len(parts) != 4 || parts[0] != "MW2" {
		return "", "", "", fmt.Errorf("invalid MW2 connection token")
	}
	centralIP = strings.TrimSpace(parts[1])
	token = strings.TrimSpace(parts[2])
	fingerprint = strings.ToLower(strings.TrimSpace(parts[3]))
	if net.ParseIP(centralIP) == nil {
		return "", "", "", fmt.Errorf("invalid central IP in token")
	}
	if len(token) < 32 || len(fingerprint) != 64 {
		return "", "", "", fmt.Errorf("invalid MW2 connection token")
	}
	for _, r := range fingerprint {
		if !strings.ContainsRune("0123456789abcdef", r) {
			return "", "", "", fmt.Errorf("invalid TLS fingerprint in token")
		}
	}
	return centralIP, token, fingerprint, nil
}
